### ISSUE TITLE
AS4 compliance

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/peppol-php#138]

**Comment by michielbdejong** [comment]
Setting up c2/3.pondersource.net for testing with the CEF Digital AS4 testbed

**Comment by michielbdejong** [comment]
`docker run -v /root/tls:/tls -p 443:443 -it logger`

**Comment by michielbdejong** [comment]
Ran https://edelconf.westeurope.cloudapp.azure.com:9001/viewJob?id=9284&showHistory=true and saw this on c2:
```
POST /as4/
CHUNK ------=_Part_35_1614928472.1665496574041
Content-Type: application/soap+xml; charset=utf-8

<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope"><env:Header><ns2:Messaging xmlns:ns2="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope" soapenv:mustUnderstand="true">
    <ns2:UserMessage>
        <ns2:MessageInfo>
            <ns2:Timestamp>2022-10-11T13:56:14.033Z</ns2:Timestamp>
            <ns2:MessageId>20695007-967c-4eec-bd82-af51ccb51705@mindertestbed.org</ns2:MessageId>
        </ns2:MessageInfo>
        <ns2:PartyInfo>
            <ns2:From>
                <ns2:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:unregistered">minder</ns2:PartyId>
                <ns2:Role>http://www.esens.eu/as4/conformancetest/testdriver</ns2:Role>
            </ns2:From>
            <ns2:To>
                <ns2:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:unregistered">pondersource-c2</ns2:PartyId>
                <ns2:Role>http://www.esens.eu/as4/conformancetest/sut</ns2:Role>
            </ns2:To>
        </ns2:PartyInfo>
        <ns2:CollaborationInfo>
            <ns2:Service>http://www.esens.eu/as4/conformancetest</ns2:Service>
            <ns2:Action>Submit</ns2:Action>
            <ns2:ConversationId>823788</ns2:ConversationId>
        </ns2:CollaborationInfo>
        <ns2:MessageProperties>
            <ns2:Property name="FromPartyIdType">urn:oasis:names:tc:ebcore:partyid-type:unregistered</ns2:Property>
            <ns2:Property name="ToPartyIdType">urn:oasis:names:tc:ebcore:partyid-type:unregistered</ns2:Property>
            <ns2:Property name="MessageId">41ad56dd-7d16-4e85-bbf5-44920f16e4fb@mindertestbed.org</ns2:Property>
<ns2:Property name="ConversationId">823788</ns2:Property>
<ns2:Property name="Service">SRV_SIMPLE_ONEWAY</ns2:Property>
<ns2:Property name="Action">ACT_SIMPLE_ONEWAY</ns2:Property>
<ns2:Property name="ToPartyId">pondersource-c3</ns2:Property>
<ns2:Property name="ToPartyRole">http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/responder</ns2:Property>
<ns2:Property name="FromPartyId">pondersource-c2</ns2:Property>
<ns2:Property name="FromPartyRole">http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/initiator</ns2:Property>
<ns2:Property name="originalSender">C1</ns2:Property>
<ns2:Property name="finalRecipient">C4</ns2:Property>
        </ns2:MessageProperties>
        <ns2:PayloadInfo>
            <ns2:PartInfo href="cid:xmlpayload@minder">
<ns2:PartProperties><ns2:Property name="MimeType">application/xml</ns2:Property>
</ns2:PartProperties>
</ns2:PartInfo>
<ns2:PartInfo href="cid:custompayload@minder">
<ns2:PartProperties><ns2:Property name="MimeType">application/octet-stream</ns2:Property>
</ns2:PartProperties>
</ns2:PartInfo>

        </ns2:PayloadInfo>
    </ns2:UserMessage>
</ns2:Messaging></env:Header><env:Body/></env:Envelope>
------=_Part_35_1614928472.1665496574041
Content-Type: application/xml
Content-ID: <xmlpayload@minder>

<min><der>sample</der></min>
------=_Part_35_1614928472.1665496574041
Content-Type: application/octet-stream
Content-ID: <custompayload@minder>

!! Modify me after submission, if you dare!!
------=_Part_35_1614928472.1665496574041--
END
```

**Comment by michielbdejong** [comment]
Next: make https://c3.pondersource.net/index.php/apps/peppolnext/api/v1 appear as https://c3.pondersource.net/as4

**Comment by michielbdejong** [comment]
I can do that with the logger

**Comment by michielbdejong** [comment]
`docker run --it --rm --network=testnet -p 443:443 -v /root/tls:/tls -v $PEPPOL_PHP_DIR:/var/www/html/apps/peppol-php logger /bin/bash`

**Comment by michielbdejong** [comment]
`[Rivet 3] 	Wait For Signal:as4-adapter|8.messageReceived(byte[])`

**Comment by michielbdejong** [comment]
Line 45 of https://edelconf.westeurope.cloudapp.azure.com:9001/viewTestCase?id=46&showJobs=true suggests that it's waiting for the message to hit the AS4 interceptor.

**Comment by michielbdejong** [comment]
Working on this in the `dev` branch

**Comment by michielbdejong** [comment]
` curl -d'@./experiments/as4-testbed/testMsg.xml' https://c2.pondersource.net/as4`
```
<li>Message: String could not be parsed as XML</li>
<li>File: /var/www/html/apps/peppol-php/nextcloud-app/peppolnext/lib/Controller/MessageApiController.php</li>
<li>Line: 390</li>
```

**Comment by michielbdejong** [comment]
hm, seems to be fixed after a restart:
```
./scripts/clean.sh 
./scripts/run-testbed-node-c2.sh 
```

**Comment by michielbdejong** [comment]
It seems the logger is stripping newlines.
Maybe I should write a logger in php instead of in js

**Comment by michielbdejong** [comment]
`curl --data-binary '@./experiments/as4-testbed/testMsg.xml' -H'Content-Type: multipart/related; boundary="------=_Part_3-9at_869791064.1665565057596"; type="application/soap+xml"; charset=UTF-8' https://c2.pondersource.net/as4`

**Comment by michielbdejong** [comment]
next error:
```
Value at OCA\\PeppolNext\\PonderSource\\SBD\\StandardBusinessDocument is expected to be an object of class OCA\\PeppolNext\\PonderSource\\UBL\\Invoice\\Invoice but is of type string","userAgent":"curl/7.74.0","version":"24.0.6.1","exception":{"Exception":"JMS\\Serializer\\Exception\\InvalidArgumentException","Message":"Value at OCA\\PeppolNext\\PonderSource\\SBD\\StandardBusinessDocument is expected to be an object of class OCA\\PeppolNext\\PonderSource\\UBL\\Invoice\\Invoice but is of type string
```
sending sample invoice for now to work around this.
Next error: https://13.81.109.44:15000/as4Interceptor cert is not valid for host 13.81.109.44

**Comment by michielbdejong** [comment]
Next: POST https://edelconf.westeurope.cloudapp.azure.com:15000/as4Interceptor` resulted in a `400 Bad Request` response

**Comment by michielbdejong** [comment]
when trying the Java->PHP demo in the dev branch, now seeing:
```
Message: Argument 1 passed to JMS\Serializer\Serializer::deserialize() must be of the type string, null given, called in /var/www/html/apps/peppol-php/nextcloud-app/peppolnext/lib/EnvelopeReader.php on line 9 in file &#039;/var/www/html/apps/peppol-php/nextcloud-app/peppolnext/vendor/jms/serializer/src/Serializer.php&#039; line 171

**Comment by michielbdejong** [comment]
Picking this back up now. Will try what happens when I send c2 -> c3 directly

**Comment by michielbdejong** [comment]
I'm resizing c2 because it seems to be getting stuck on `docker ps`

**Comment by michielbdejong** [comment]
OK, now set up `./scripts/run-testbed-node-c[2|3].sh` on c[2|3].pondersource.net and trying out the curl command from https://github.com/pondersource/peppol-php/issues/138#issuecomment-1278614168

**Comment by michielbdejong** [comment]
And `curl -k -d'hi' https://nc1.docker/index.php/apps/peppolnext/api/v1/testbed`
But I'm having weird and annoying latency problems so not getting very far yet.

**Comment by michielbdejong** [comment]
```
curl -k --data-binary '@./experiments/as4-testbed/msgToInterceptor.xml' -H'Message-Id: <634963881a41a>' -H 'MIME-Version: 1.0' -H 'Content-Type: multipart/related;    boundary="----=_Part_6349638264546";    type="application/soap+xml"; charset=UTF-8' https://nc1.docker/index.php/apps/peppolnext/api/v1/testbed
```

**Comment by michielbdejong** [comment]
On c3 this returns instantly, on c2 it hangs.

**Comment by michielbdejong** [comment]
On c2:
```
docker run -d --network=host -v /root/tls:/tls re-signing-gateway
```

From laptop:
```
curl --data-binary '@./experiments/as4-testbed/testMsg.xml' -H'Content-Type: multipart/related; boundary="------=_Part_3-9at_869791064.1665565057596"; type="application/soap+xml"; charset=UTF-8' https://c2.pondersource.net/as4
```

**Comment by michielbdejong** [comment]
Next:
```
[Tue Oct 25 14:23:11.678227 2022] [php7:notice] [pid 12] [client 185.217.210.83:49777] PHP Fatal error:  Uncaught JMS\\Serializer\\Exception\\XmlErrorException: [FATAL] Start tag expected, '<' not found\n in  (line: 1, column: 1) in /var/www/html/vendor/jms/serializer/src/XmlDeserializationVisitor.php:106\nStack trace:\n#0 /var/www/html/vendor/jms/serializer/src/Serializer.php(245): JMS\\Serializer\\XmlDeserializationVisitor->prepare()\n#1 /var/www/html/vendor/jms/serializer/src/Serializer.php(180): JMS\\Serializer\\Serializer->visit()\n#2 /var/www/html/lib/EnvelopeReader.php(13): JMS\\Serializer\\Serializer->deserialize()\n#3 /var/www/html/lib/PayloadReader.php(15): OCA\\PeppolNext\\EnvelopeReader::readEnvelope()\n#4 /var/www/html/lib/PonderSource/AS4.php(274): OCA\\PeppolNext\\PayloadReader::readPayload()\n#5 /var/www/html/c2.php(22): OCA\\PeppolNext\\PonderSource\\AS4->handleAs4()\n#6 {main}\n  thrown in /var/www/html/vendor/jms/serializer/src/XmlDeserializationVisitor.php on line 106
```

**Comment by michielbdejong** [comment]
```
[MIME PARTS]
array (
  0 =>
  array (
    'Lines' => 
    array (
    ),
  ),
  1 =>   array (
    'Lines' =>     array (
      0 => '<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope"><env:Header><ns2:Messaging xmlns:ns2="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope" soapenv:mustUnderstand="true">',
      1 => '    <ns2:UserMessage>',
      2 => '        <ns2:MessageInfo>',
      3 => '            <ns2:Timestamp>2022-10-12T08:57:37.587Z</ns2:Timestamp>',
      4 => '            <ns2:MessageId>135f0fbc-36dd-421c-85a1-1592cf9bdf8b@mindertestbed.org</ns2:MessageId>',
      5 => '        </ns2:MessageInfo>',
      6 => '        <ns2:PartyInfo>',
      7 => '            <ns2:From>',
      8 => '                <ns2:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:unregistered">minder</ns2:PartyId>',
      9 => '                <ns2:Role>http://www.esens.eu/as4/conformancetest/testdriver</ns2:Role>',
      10 => '            </ns2:From>',
      11 => '            <ns2:To>',
      12 => '                <ns2:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:unregistered">pondersource-c2</ns2:PartyId>',
      13 => '                <ns2:Role>http://www.esens.eu/as4/conformancetest/sut</ns2:Role>',
      14 => '            </ns2:To>',
      15 => '        </ns2:PartyInfo>',
      16 => '        <ns2:CollaborationInfo>',
      17 => '            <ns2:Service>http://www.esens.eu/as4/conformancetest</ns2:Service>',
      18 => '            <ns2:Action>Submit</ns2:Action>',
      19 => '            <ns2:ConversationId>743929</ns2:ConversationId>',
      20 => '        </ns2:CollaborationInfo>',
      21 => '        <ns2:MessageProperties>',
      22 => '            <ns2:Property name="FromPartyIdType">urn:oasis:names:tc:ebcore:partyid-type:unregistered</ns2:Property>',
      23 => '            <ns2:Property name="ToPartyIdType">urn:oasis:names:tc:ebcore:partyid-type:unregistered</ns2:Property>',
      24 => '            <ns2:Property name="MessageId">91fa5c43-6396-43fd-ae27-1aedcd641dfc@mindertestbed.org</ns2:Property>',
      25 => '<ns2:Property name="ConversationId">743929</ns2:Property>',
      26 => '<ns2:Property name="Service">SRV_SIMPLE_ONEWAY</ns2:Property>',\n      27 => '<ns2:Property name="Action">ACT_SIMPLE_ONEWAY</ns2:Property>',\n      28 => '<ns2:Property name="ToPartyId">pondersource-c3</ns2:Property>',\n      29 => '<ns2:Property name="ToPartyRole">http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/responder</ns2:Property>',\n      30 => '<ns2:Property name="FromPartyId">pondersource-c2</ns2:Property>',\n      31 => '<ns2:Property name="FromPartyRole">http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/initiator</ns2:Property>',\n      32 => '<ns2:Property name="originalSender">C1</ns2:Property>',\n      33 => '<ns2:Property name="finalRecipient">C4</ns2:Property>',\n      34 => '        </ns2:MessageProperties>',\n      35 => '        <ns2:PayloadInfo>',\n      36 => '            <ns2:PartInfo href="cid:xmlpayload@minder">',\n      37 => '<ns2:PartProperties><ns2:Property name="MimeType">application/xml</ns2:Property>',\n      38 => '</ns2:PartProperties>',\n      39 => '</ns2:PartInfo>',\n      40 => '<ns2:PartInfo href="cid:custompayload@minder">',\n      41 => '<ns2:PartProperties><ns2:Property name="MimeType">application/octet-stream</ns2:Property>',\n      42 => '</ns2:PartProperties>',\n      43 => '</ns2:PartInfo>',\n      44 => '',\n      45 => '        </ns2:PayloadInfo>',\n      46 => '    </ns2:UserMessage>',\n      47 => '</ns2:Messaging></env:Header><env:Body/></env:Envelope>',
      48 => '',
    ),
    'Content-Type' => 'application/soap+xml; charset=utf-8',
  ),
  2 => 
 array (
    'Lines' => \n    array (
      0 => '<min><der>sample</der></min>',
      1 => '',
    ),
    'Content-Type' => 'application/xml',
  ),
  3 => 
  array (
    'Lines' => \n    array (\n      0 => '!! Modify me after submission, if you dare!!',
      1 => '',\n    ),
    'Content-Type' => 'application/octet-stream',\n  ),
  4 => \n  array (\n    'Lines' => \n    array (\n    ),\n  ),\n)
```

**Comment by michielbdejong** [comment]
I can try to improve my message to the interceptor, but if it's just responding with 500s I may have to switch to our own test suite involving Phase4 + PeppolNext

**Comment by michielbdejong** [comment]
This is too hard and too time-consuming. We'll leave it for now, and then use our own test suite to pitch Phase4 and PeppolNext against each other.
