### ISSUE TITLE
PHP -> CYB -> Java: in sender, configure the gateway; whitelist sender in gateway

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/peppol-php#145]

**Comment by michielbdejong** [comment]
I got the gateway executing the AS4 handling code that I extracted from MessageApiController.
Next step: send a message into it from AS4

**Comment by michielbdejong** [comment]
Got that working, using mod_rewrite in apache-php to make /as4 go to /index.php. now seeing how far through the code it's getting. Next:
```
PHP Notice:  Undefined property: OCA\\PeppolNext\\PonderSource\\AS4::$messageService in /var/www/html/lib/PonderSource/AS4.php on line 276
```

**Comment by michielbdejong** [comment]
Next:
```
 PHP Fatal error:  Uncaught Error: Class 'OCA\\PeppolNext\\PonderSource\\MessagePartNRInformation' not found in /var/www/html/lib/PonderSource/AS4.php:299\nStack trace:\n#0 /var/www/html/index.php(18): OCA\\PeppolNext\\PonderSource\\AS4->handleAs4()\n#1 {main}\n  thrown in /var/www/html/lib/PonderSource/AS4.php on line 299
```

**Comment by michielbdejong** [comment]
```
[Wed Oct 19 12:54:35.633691 2022] [php7:notice] [pid 14] [client 192.168.16.5:59714] PHP Fatal error:  Uncaught Error: Class 'GuzzleHttp\\Client' not found in /var/www/html/lib/PonderSource/AS4.php:508\nStack trace:\n#0 /var/www/html/lib/PonderSource/AS4.php(316): OCA\\PeppolNext\\PonderSource\\AS4->as4SendWithIdentifier()\n#1 /var/www/html/index.php(18): OCA\\PeppolNext\\PonderSource\\AS4->handleAs4()\n#2 {main}\n  thrown in /var/www/html/lib/PonderSource/AS4.php on line 508
```

**Comment by michielbdejong** [comment]
The invoice successfully arrives at the server. Rudimentary whitelist added.
